config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  root to: 'static_pages#root'

  namespace :api do
    resources :blogs do
      resources :posts, only: [:index]
      resource :follow, only: [:create, :destroy]
    end
    resources :users, only: [:show]
    resources :follows, only: [:index, :create, :destroy]
    resources :posts, except: [:index]
    resources :comments
    resources :recommendations, only: [:index]
  end

  resources :users
  # resources :blogs do
  #   resources :posts do
  #     resources :comments
  #   end
  # end
  resource :session

  # to create a new guest account
  post '/guest', to: 'users#new_guest', as: :new_guest
end

app/models/blog.rb
class Blog < ActiveRecord::Base

  validates :path, null: false, length: {maximum: 30}
  validates :title, null: false, length: {maximum: 255}
  validates :tagline, length: {maximum: 255, allow_nil: true}

  has_many :permissions, inverse_of: :blog
  has_many :staff, through: :permissions, source: :user
  has_many :posts, dependent: :destroy
  has_many :follows, dependent: :destroy
  has_many :followers, through: :follows, source: :user, dependent: :destroy

  def self.most_followed(page = 1, per = 5)
    Blog.joins(:follows)
        .group("blogs.id")
        .page(page).per(per)
        .order("COUNT(follows) DESC")
  end

end

app/controllers/api/blogs_controller.rb
class Api::BlogsController < Api::ApiController
  before_action :require_permissions!, only: [:edit, :update]

  def create
    blog = Blog.new(blog_params)
    permission = blog.permissions.new(
      user_id: current_user.id,
      role: 0,
      is_moderator: true
    )
    if blog.save
      render json: blog
    else
      render json: blog.errors.full_messages, status: :unprocessable_entity
    end
  end

  def show
    @blog = Blog.find(params[:id])
    @page = params[:page] || 1
    render :show
  end

  def edit
    @blog = Blog.find(params[:id])
    @posts = @blog.posts.page(params[:page] || 1)
    render :edit
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update_attributes(blog_params)
      render json: @blog
    else
      render json: @blog.errors.full_messages, status: :unprocessable_entity
    end
  end

  def index
    render json: current_user.blogs
  end

  private

  def blog_params
    params.require(:blog).permit(:path, :title, :tagline)
  end

  def require_permissions!
    blog = Blog.find(params[:id])
    return if blog.staff.include?(current_user)
    flash[:errors] = ["You aren't authorized to do that!"]
    redirect_to blog_url(blog)
  end

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/new.html.erb
<form class="form" action="<%= blogs_url %>" method="post">
  <%= auth_token %>

  <label>Path
    <input type="text" name="blog[path]">
  </label>

  <label>Title
    <input type="text" name="blog[title]">
  </label>

  <label>Tagline
    <input type="text" name="blog[tagline]">
  </label>

  <input type="submit" value="Submit">
</form>

app/views/blogs/show.html.erb
<div>
  <h1><%= @blog.title %></h1>
  at <%= @blog.path %><br>
  <em>"<%= @blog.tagline %>"</em>
</div>

<% @blog.posts.each do |post| %>
  <h3><%= link_to post.title, blog_post_url(blog_id: @blog.id, id: post.id) %>
  (<%= post.comment_count %> comments)</h3>
  <%= simple_format(post.content) %>
<% end %>

<%= link_to "New post", new_blog_post_url(@blog) %>