config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  root to: 'static_pages#root'

  namespace :api do
    resources :blogs do
      resources :posts, only: [:index]
      resource :follow, only: [:create, :destroy]
    end
    resources :users, only: [:show]
    resources :follows, only: [:index, :create, :destroy]
    resources :posts, except: [:index]
    resources :comments
    resources :recommendations, only: [:index]
  end

  resources :users
  # resources :blogs do
  #   resources :posts do
  #     resources :comments
  #   end
  # end
  resource :session

  # to create a new guest account
  post '/guest', to: 'users#new_guest', as: :new_guest
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  validates :content, :post, presence: true

  belongs_to :post, inverse_of: :comments, foreign_key: :post_id
  belongs_to :author, class_name: "User", foreign_key: :author_id
  belongs_to :parent_comment, class_name: "Comment"

  has_many :child_comments, class_name: "Comment", foreign_key: :parent_comment_id

end

app/controllers/api/comments_controller.rb
class Api::CommentsController < Api::ApiController
  before_action :require_permissions!, only: [:update]
  before_action :require_author_or_permissions!, only: [:destroy]

  # to get simple_format in the controller
  include ActionView::Helpers::TextHelper

  def create
    @comment = current_user.comments.new(comment_params)
    @comment.content = simple_format(@comment.content)

    if @comment.save
      render json: @comment
    else
      render json: @comment.errors.full_messages, status: :unprocessable_entity
    end
  end

  def show
    comment = Comment.find(params[:id])
    render json: comment
  end

  def update
    @comment = Post.find(params[:id])
    if @comment.update_attributes(comment_params)
      render json: @comment
    else
      render json: @comment.errors.full_messages, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id, :parent_comment_id)
  end

  def require_permissions!
    blog = Blog.find(Comment.find(params[:id]).post.blog.id)
    return if blog.staff.include?(current_user)
    flash[:errors] = ["You aren't authorized to do that!"]
    redirect_to blog_url(blog)
  end

  def require_author_or_permissions!
    comment = Comment.find(params[:id])
    return if comment.user_id == current_user.id
    blog = Blog.find(comment.post.blog.id)
    return if blog.staff.include?(current_user)
    flash[:errors] = ["You aren't authorized to do that!"]
    redirect_to blog_url(blog)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<%= simple_format(comment.content) %><br>
<%= link_to "Reply", blog_post_comment_url(id: comment.id, post_id: comment.post_id) %>
<ul>
  <% comments[comment.id].each do |child_comment| %>
    <li>
      <%= render "comments/comment", comment: child_comment, comments: comments %>
    </li>
  <% end %>
</ul>

app/views/comments/show.html.erb
<%= @comment.content %>


<form action="<%= blog_post_comments_url(post_id: @comment.post_id) %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="comment[post_id]" value="<%= @comment.post_id %>">
  <input type="hidden" name="comment[parent_comment_id]" value="<%= @comment.id %>">
  <textarea name="comment[content]" rows="16" cols="80"></textarea><br>
  <input type="submit" value="Reply">
</form>