config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  root to: 'static_pages#root'

  namespace :api do
    resources :blogs do
      resources :posts, only: [:index]
      resource :follow, only: [:create, :destroy]
    end
    resources :users, only: [:show]
    resources :follows, only: [:index, :create, :destroy]
    resources :posts, except: [:index]
    resources :comments
    resources :recommendations, only: [:index]
  end

  resources :users
  # resources :blogs do
  #   resources :posts do
  #     resources :comments
  #   end
  # end
  resource :session

  # to create a new guest account
  post '/guest', to: 'users#new_guest', as: :new_guest
end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  belongs_to :user
end
 

app/models/blog.rb
class Blog < ActiveRecord::Base

  validates :path, null: false, length: {maximum: 30}
  validates :title, null: false, length: {maximum: 255}
  validates :tagline, length: {maximum: 255, allow_nil: true}

  has_many :permissions, inverse_of: :blog
  has_many :staff, through: :permissions, source: :user
  has_many :posts, dependent: :destroy
  has_many :follows, dependent: :destroy
  has_many :followers, through: :follows, source: :user, dependent: :destroy

  def self.most_followed(page = 1, per = 5)
    Blog.joins(:follows)
        .group("blogs.id")
        .page(page).per(per)
        .order("COUNT(follows) DESC")
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  validates :content, :post, presence: true

  belongs_to :post, inverse_of: :comments, foreign_key: :post_id
  belongs_to :author, class_name: "User", foreign_key: :author_id
  belongs_to :parent_comment, class_name: "Comment"

  has_many :child_comments, class_name: "Comment", foreign_key: :parent_comment_id

end

app/models/follow.rb
class Follow < ActiveRecord::Base

  belongs_to :user
  belongs_to :blog

end

app/models/permission.rb
class Permission < ActiveRecord::Base

  # enum role: {
  #   owner: 0,
  #   administrator: 1,
  #   editor: 2,
  #   author: 3,
  #   contributor: 4
  # }

  enum role: {
    administrator: 0
  }

  validates :user_id, presence: true
  validates :blog, presence: true
  validates :is_moderator, presence: true
  before_save :owners_and_admins_are_always_moderators

  belongs_to :blog
  belongs_to :user

  private

  def owners_and_admins_are_always_moderators
    if ["owner", "administrator"].include?(role)
      is_moderator = true
    end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base

  before_create :enforce_published_at, :enforce_views

  enum status: {
    published: 0,
    draft: 1,
    pending_review: 2
  }

  belongs_to :blog
  belongs_to :author, class_name: "User", foreign_key: :author_id
  has_many :comments, dependent: :destroy

  validates :author_id, :blog_id, :content, :status, presence: true

  def comment_count
    self.comments.length
  end

  def comments_by_parent
    comments_by_parent = Hash.new { |h, k| h[k] = [] }
    self.comments.includes(:author).each do |comment|
      comments_by_parent[comment.parent_comment_id] << comment
    end
    comments_by_parent
  end

  def self.most_viewed(page = 1, per = 5)
    Post.page(page).per(per).order(views: :desc).includes(:blog)
  end

  def self.most_commented(page = 1, per = 5)
    Post.joins(:comments)
        .group("posts.id")
        .page(page).per(per)
        .order("COUNT(comments) DESC")
        .includes(:blog)
  end

  private

  def enforce_published_at
    self.published_at = Time.now if !(self.published_at) && self.status == 0
  end

  def enforce_views
    self.views = 0 unless self.views
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :password, length: {minimum: 6, allow_nil: true}
  attr_reader :password

  validates :email, presence: true, length: {maximum: 255}

  has_many :permissions, dependent: :destroy
  has_many :blogs, through: :permissions
  has_many :posts, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id
  has_many :follows
  has_many :followed_blogs, through: :follows, source: :blog
  has_many :authorizations, dependent: :destroy

  def first_name
    self.name.split.first || self.email.split("@").first
  end

  def email_md5
    return @email_md5 if @email_md5

    email_md5_obj = Digest::MD5.new
    email_md5_obj.update self.email
    @email_md5 = email_md5_obj.hexdigest
    @email_md5
  end

  def is_following?(blog)
    self.followed_blogs.include?(blog)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil unless user && user.valid_password?(password)
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :logged_in?, :email_md5

  def logged_in?
    !!current_user
  end

  # take a username on signup, devise!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )

    if @user
      sign_in(@user)
      redirect_to new_user_session_url
    else
      flash[:errors] = ["Invalid username or password."]
      redirect_to new_user_session_url
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    redirect_to new_user_registration_path
  end

  def create
    user = User.new(user_params)
    if user.save
      log_in(user)
      redirect_to root_url
    else
      flash.now[:errors] = user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def new_guest
    new_id = (User.last) ? (User.last.id + 1).to_s : "1"
    user = User.new(password: "guestguest",
                    email: "guest" + new_id + "@example.com",
                    name: "guest" + new_id)

    if user.save
      sign_in(user)
      redirect_to root_url
    else
      flash[:errors] = user.errors.full_messages
      redirect_to root_url
    end
  end

  private

  def user_params
    params.require(:user).permit(:password, :email)
  end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input type='hidden' name='authenticity_token' value='#{ form_authenticity_token }'>".html_safe
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fnordpress</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'shared/header' %>
<%= render 'shared/errors' %>

<section id='main'>
  <%= yield %>
</section>

</body>
</html>

app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <%= error %>
  <% end %>
<% end %>

app/views/shared/_header.html.erb
<header id="page-header" data-email-hash="<%= current_user.email_md5 if logged_in? %>">
  <nav class="header-nav group">
    <ul class="header-list user-login">
      <% if logged_in? %>
        <li>
          <div class="pseudo-anchor">
            <span class="avatar-container">
              <img src="http://www.gravatar.com/avatar/<%= current_user.email_md5 %>?d=identicon">
            </span>
            Hello.
          </div>
        </li>
        <li><%= button_to "Log out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li class="guest"><%= button_to "Log in as guest", new_guest_url %></li>
        <li><%= link_to "Log in", new_user_session_path %></li>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
      <% end %>
      </li>
    </ul>
    <% if logged_in? %>
      <ul class="header-list user-header-links group">
        <li><a href="#">Dashboard</a>
        </li>
        <li id="header-my-blogs">
          <a href="#me">My Blogs</a>
          <ul class="dropdown blogs-dropdown">
            <% current_user.blogs.each do |blog| %>
              <li data-id="<%= blog.id %>">
                <a href="#blogs/<%= blog.id %>"> <%= blog.title %> </a>
                <ul class="nested-dropdown blogs-nested-dropdown">
                  <li>
                    <a href="#blogs/<%= blog.id %>/posts/new">New Post</a>
                  </li>
                  <li>
                    <a href="#blogs/<%= blog.id %>/edit">Edit Blog</a>
                  </li>
                </ul>
              </li>
            <% end %>
          </ul>
        </li>
      </ul>
    <% end %>

    <strong>FNORDPRESS</strong>

    <ul class="header-list blog-header invis group">
      <li class="blog-header-li">
      </li>
    </ul>
  </nav>
</header>